# Welcome to Jekyll!
#

# Site settings
title: Annie Yang
description: |
  Human Bean\\
  Software Engineer\\
  Writer
owner: Annie Yang # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: annie.s.yang16@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ayangster.github.io/" # the base hostname & protocol for your site
social:
  # twitter: https://twitter.com/<username>
  github: https://github.com/ayangster
  linkedin-square: https://linkedin.com/in/annie-yang-1b458269
  # facebook-official: https://facebook.com/annie.bananie.yang
  # google-plus-square: https://plus.google.com/u/0/+<username>
  email: annie.s.yang16@gmail.com
  #flickr:
  instagram: https://www.instagram.com/ayangster12/
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  tumblr-square: http://lifeasannieknowsit.tumblr.com/
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
